// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAunqOHcA0SebEf2C8w0r_GFDr2aCwrx2A',
    appId: '1:369065355278:web:b138cd80b2e299dacd745f',
    messagingSenderId: '369065355278',
    projectId: 'task-management-7b425',
    authDomain: 'task-management-7b425.firebaseapp.com',
    storageBucket: 'task-management-7b425.appspot.com',
    measurementId: 'G-HC6JR7MWEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxh-cYJLx3OhSCwl8aso9i6mIpvUvC00I',
    appId: '1:369065355278:android:47089506c7bd58e9cd745f',
    messagingSenderId: '369065355278',
    projectId: 'task-management-7b425',
    storageBucket: 'task-management-7b425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw30XiBIxu0GmQqzKJDzVEaTLtY_RoNeM',
    appId: '1:369065355278:ios:9011c2f6d4fff0f3cd745f',
    messagingSenderId: '369065355278',
    projectId: 'task-management-7b425',
    storageBucket: 'task-management-7b425.appspot.com',
    androidClientId: '369065355278-ffcmicd1lqi1pe77libeab9kjg2autkf.apps.googleusercontent.com',
    iosClientId: '369065355278-7m7aduvvv0bug59ge038h824n22ljj30.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );
}
